### ISSUE TITLE
Unexpected error in setup_connection(): could not convert string to float: '8.0.2'

### ISSUE THREAD

**Issue by GabrielRF** [beveradb/pysonofflan#96] opened 2019-08-03 23:36 UTC
* pySonoffLAN version: 0.3.0
* Python version: 3.6.8
* Operating System: Ubuntu 18.04.2 LTS 

### Description

I tried to run  `pysonofflan --host 192.168.1.49 off` on my Sonoff R3 with firmware `3.3.0` and I get an error. This happens also when I try to turn my device on. 

The output:
```
2019-08-03 20:32:46,411 - info: Initialising SonoffSwitch with host 192.168.1.49
2019-08-03 20:32:46,411 - error: Unexpected error in setup_connection(): could not convert string to float: '8.0.2'
```

**Comment by Maxmudjon** [comment] 2019-08-18 10:14
C:\Users\Maxmudjon\Desktop\pysonofflan>pysonofflan --host 192.168.1.16 state
2019-08-18 15:13:25,899 - info: Initialising SonoffSwitch with host 192.168.1.16
2019-08-18 15:13:25,901 - error: Unexpected error in setup_connection(): could not convert string to float: '8.0.2'

**Comment by mattsaxon** [comment] 2019-08-18 12:13
this issue is fixed here already if you want to try the upstream https://github.com/barbieri/pysonofflan/tree/fixes

However if you are on firmeware v3 or above, you should use  my repo here https://github.com/mattsaxon/pysonofflan

**Comment by GabrielRF** [comment] 2019-08-18 13:15
@mattsaxon I'll try that asap!
Thank you very much!

**Comment by GabrielRF** [comment] 2019-08-19 16:26
@mattsaxon Did not work.. Same error as before

**Comment by tjoepies** [comment] 2019-09-07 14:56
the problem is here: `websockets.__version__` contains `"8.0.2"` and the function `float()` doesn't accept that. I'm no python programmer, but this is what I was able to find by attempting to debug.

```
--- sonoffdevice.py.original    2019-09-07 16:43:11.321016141 +0200
+++ sonoffdevice.py     2019-09-07 16:44:17.790907340 +0200
@@ -5,6 +5,7 @@
 import asyncio
 import json
 import logging
+import pdb
 from typing import Callable, Awaitable, Dict

 import traceback
@@ -81,6 +82,7 @@
             self.logger.debug('SonoffDevice loop ended, returning')

     async def setup_connection(self, retry):
+        pdb.set_trace()
         self.logger.debug('setup_connection is active on the event loop')

         retry_count = 0
```
stepping into line sonoffdevice.py:94 `await self.client.connect()` throws the error at line client.py:325

The problem seems to appear on these lines:

```
$ grep -n websockets.__version__ *
client.py:123:        if float(websockets.__version__) < 7.0:
client.py:142:        if float(websockets.__version__) < 7.0:
client.py:154:        if float(websockets.__version__) >= 7.0:
client.py:209:        if float(websockets.__version__) < 7.0:
client.py:221:        if float(websockets.__version__) >= 7.0:
client.py:258:        if float(websockets.__version__) < 7.0:
client.py:325:            if float(websockets.__version__) >= 7.0:
```
I tried replacing `websockets.__version__` with `"8.0"` but pysonofflan is hanging.

**Comment by mattsaxon** [comment] 2019-09-07 15:46
I’m suspecting you have v3 firmware on the device, if so you should use my fork which is for v3 and above. This repo only support version 2 of the firmware and prior

**Comment by tjoepies** [comment] 2019-09-07 15:58
> I’m suspecting you have v3 firmware on the device, if so you should use my fork which is for v3 and above. This repo only support version 2 of the firmware and prior

hello, I did clone your [repo](https://github.com/barbieri/pysonofflan/tree/fixes) and yes I do have firmware version 3.3.0 (PSF-B01-GL). Should I create an issue on your repo?

**Comment by mattsaxon** [comment] 2019-09-07 16:00
Yes please. However the could not convert strong to float doesn’t occur with the code in my repo, so are you referring to a different issue?

Sent from my iPhone

On 7 Sep 2019, at 16:58, tjoepies <notifications@github.com<mailto:notifications@github.com>> wrote:


I’m suspecting you have v3 firmware on the device, if so you should use my fork which is for v3 and above. This repo only support version 2 of the firmware and prior

hello, I did clone your repo<https://github.com/barbieri/pysonofflan/tree/fixes> and yes I do have firmware version 3.3.0 (PSF-B01-GL). Should I create an issue on your repo?

**Comment by tjoepies** [comment] 2019-09-07 16:29
> Yes please. However the could not convert strong to float doesn’t occur with the code in my repo, so are you referring to a different issue?

hello, I ran `git clone https://github.com/barbieri/pysonofflan.git` and for some reason the files that were updated, does not reflect the websockets version handling, update. I had to use wget to download the specific updated files and now this issue disappeared. But I'm seeing a new problem. It just hangs. same as I mentioned before with this. Excuse for my ignorance here but how do I create a ticket or issue on your repo?

**Comment by aleksey2000** [comment] 2019-09-07 18:30
Hi all, temporary solution is the following:

In client.py replace: float(websockets.__version__) with float(websockets.__version__[:3]).

E.g: if float(websockets.__version__[:3]) < 7.0:

**Comment by mattsaxon** [comment] 2019-09-08 10:49
@tjoepies raise a new issue here https://github.com/mattsaxon/pysonofflan/issues/new

Strange about the behaviour of your git clone command, can you ensure that it is not this that is causing the issue before raising the issue, i.e. make sure you have all the correct code.

**Comment by tjoepies** [comment] 2019-09-09 19:57
> @tjoepies raise a new issue here https://github.com/mattsaxon/pysonofflan/issues/new
> 
> Strange about the behaviour of your git clone command, can you ensure that it is not this that is causing the issue before raising the issue, i.e. make sure you have all the correct code.

hello @mattsaxon

I created one [here.](https://github.com/mattsaxon/pysonofflan/issues/5)

**Comment by mattsaxon** [comment] 2019-12-30 04:32
closed this issue as covered in R3 repository fork

**Closed by mattsaxon** 2019-12-30 04:32 UTC
Labels: upstream
